### ISSUE TITLE
TS-023 - Atualização nas tabelas Product e User

### ISSUE THREAD

**Issue by marchingbeagle** [marchingbeagle/max-sane-satc#24]
User
Adicionar o campo de "email" do tipo texto
Adicionar o campo de "cpf" do ti1po texto
Adicionar o campo de "phone_number" do tipo texto

Product
Adicionar o campo de "description"  do tipo texto
Adicionar o campo de "use_case" do tipo inteiro

**Comment by GabrielWDuarte** [comment]
Task Concluída.
